In [2]:
# Import all the libraries that we shall be using
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.cluster import KMeans
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [3]:
df_all = pd.read_csv('all.csv')
df_aml = pd.read_csv('aml.csv')

In [4]:
df_all.head()

,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,AFFX-BioB-5_st,...,U48730_at,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at
0,-214,-153,-58,88,-295,-558,199,-176,252,206,...,185,511,-125,389,-37,793,329,36,191,-37
1,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,169,837,-36,442,-17,782,295,11,76,-14
2,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,315,1199,33,168,52,1138,777,41,228,-41
3,-135,-114,265,12,-419,-585,158,-253,49,31,...,240,835,218,174,-110,627,170,-50,126,-91
4,-106,-125,-76,168,-230,-284,4,-122,70,252,...,156,649,57,504,-26,250,314,14,56,-25

In [29]:
df_all.describe()

,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,AFFX-BioB-5_st,...,U48730_at,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at
count,27.000000,27.000000,27.000000,27.000000,27.000000,27.00000,27.000000,27.000000,27.000000,27.000000,...,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,-136.000000,-158.000000,-19.555556,147.481481,-277.444444,-435.00000,-21.814815,-179.296296,92.814815,75.592593,...,177.518519,732.555556,8.148148,420.851852,-21.000000,769.222222,340.185185,23.518519,243.592593,-31.259259
std,109.584881,77.602538,130.142919,110.515356,108.489749,143.80275,223.257533,86.542926,70.972387,198.208759,...,85.537833,268.614584,84.565270,552.028755,39.601865,405.346322,230.817450,33.900727,205.001737,32.052352
min,-476.000000,-327.000000,-307.000000,-36.000000,-541.000000,-790.00000,-479.000000,-463.000000,-37.000000,-215.000000,...,30.000000,224.000000,-178.000000,36.000000,-110.000000,195.000000,41.000000,-50.000000,-2.000000,-94.000000
25%,-141.500000,-216.000000,-99.500000,63.000000,-359.000000,-554.50000,-152.000000,-199.500000,41.500000,-60.500000,...,120.000000,578.000000,-42.000000,173.000000,-45.000000,576.500000,206.500000,9.000000,121.000000,-42.500000
50%,-112.000000,-147.000000,-50.000000,149.000000,-262.000000,-402.00000,-36.000000,-174.000000,96.000000,31.000000,...,176.000000,678.000000,13.000000,249.000000,-18.000000,672.000000,314.000000,21.000000,193.000000,-25.000000
75%,-78.500000,-99.000000,60.500000,249.000000,-192.000000,-331.50000,115.500000,-134.000000,131.000000,199.500000,...,232.500000,908.500000,54.500000,448.500000,-1.500000,924.000000,398.000000,38.500000,258.000000,-15.000000
max,17.000000,-49.000000,265.000000,316.000000,-127.000000,-221.00000,419.000000,-24.000000,252.000000,506.000000,...,356.000000,1221.000000,218.000000,2527.000000,52.000000,1799.000000,1109.000000,115.000000,807.000000,36.000000

In [5]:
df_aml.describe()

,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,AFFX-BioB-5_st,...,U48730_at,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,-83.727273,-132.181818,-11.272727,264.636364,-274.363636,-449.545455,-97.000000,-254.909091,114.363636,201.818182,...,181.818182,795.727273,10.454545,345.818182,-17.727273,1114.090909,325.181818,8.636364,1144.545455,-24.181818
std,105.120969,71.018051,84.586158,92.587551,122.400386,118.151905,210.299786,81.176911,110.180100,226.727510,...,87.096289,371.314447,58.323861,138.405793,50.485822,583.742316,155.581373,20.761853,1105.109077,28.484446
min,-318.000000,-252.000000,-125.000000,101.000000,-407.000000,-566.000000,-351.000000,-390.000000,-82.000000,-131.000000,...,36.000000,336.000000,-58.000000,139.000000,-112.000000,279.000000,51.000000,-26.000000,133.000000,-67.000000
25%,-129.500000,-189.000000,-63.500000,211.500000,-373.000000,-519.500000,-285.000000,-302.500000,38.000000,26.500000,...,124.500000,542.000000,-38.500000,246.000000,-40.000000,744.500000,264.500000,-10.500000,316.500000,-39.500000
50%,-32.000000,-116.000000,-37.000000,312.000000,-324.000000,-478.000000,-31.000000,-240.000000,119.000000,176.000000,...,173.000000,737.000000,-15.000000,334.000000,-13.000000,987.000000,295.000000,12.000000,662.000000,-31.000000
75%,-12.000000,-89.500000,25.500000,327.500000,-189.500000,-417.000000,21.500000,-212.500000,179.500000,339.500000,...,229.500000,973.500000,60.000000,452.500000,22.500000,1430.000000,351.500000,24.000000,2021.000000,-2.500000
max,15.000000,-20.000000,136.000000,392.000000,-51.000000,-155.000000,324.000000,-105.000000,283.000000,561.000000,...,348.000000,1653.000000,102.000000,573.000000,42.000000,2315.000000,627.000000,39.000000,3193.000000,23.000000

In [7]:
df_all.columns

Index(['AFFX-BioB-5_at', 'AFFX-BioB-M_at', 'AFFX-BioB-3_at', 'AFFX-BioC-5_at',
       'AFFX-BioC-3_at', 'AFFX-BioDn-5_at', 'AFFX-BioDn-3_at',
       'AFFX-CreX-5_at', 'AFFX-CreX-3_at', 'AFFX-BioB-5_st',
       ...
       'U48730_at', 'U58516_at', 'U73738_at', 'X06956_at', 'X16699_at',
       'X83863_at', 'Z17240_at', 'L49218_f_at', 'M71243_f_at', 'Z78285_f_at'],
      dtype='object', length=7129)

In [99]:
#유전자 한개에 대해서 aml과 all에 대한 ttest
import scipy.stats
from pandas import DataFrame as df

label_name=[]
pvalue=[]
statistic=[]
tu=[] #라벨과 pvalue
tu1=[] #라벨과 statistic
tu2=[] #라벨과 statistic, pvalue


for i in range(len(df_all.columns)):
    lname=df_all.columns[i]
    ttest=scipy.stats.ttest_ind(df_all[lname], df_aml[lname])
    
    if(ttest[0]<0):
        value=abs(ttest[0])
    temp1=(lname,value)
    tu1.append(temp1)
    
    abs(ttest[1]) #절대값
    if(ttest[1]<0.01):
        temp=(lname,ttest[1])
        temp2=(lname,value,ttest[1])
        tu.append(temp)
        tu2.append(temp2)

In [110]:
tu.sort(key=lambda t:t[1])

In [112]:
print(tu[0:10])

[('U50136_rna1_at', 1.3823856573320467e-10), ('X95735_at', 2.4355284732778464e-10), ('M55150_at', 6.577977412771947e-10), ('M16038_at', 9.846897254435025e-09), ('Y12670_at', 1.0059685670219272e-08), ('M23197_at', 1.5145322164300762e-08), ('D49950_at', 3.610124227026674e-08), ('X17042_at', 6.156940644228055e-08), ('U82759_at', 7.15710601890389e-08), ('M84526_at', 8.917169547067967e-08)]

In [103]:
tu1.sort(key=lambda t:-t[1])

In [113]:
print(tu1[0:10])

[('U50136_rna1_at', 8.86979372138852), ('U50146_at', 8.86979372138852), ('X95735_at', 8.66965836922781), ('X95826_at', 8.66965836922781), ('M55150_at', 8.322670912416534), ('M55153_at', 8.322670912416534), ('M55172_at', 8.322670912416534), ('M55210_at', 8.322670912416534), ('M16038_at', 7.401006458180494), ('M16279_at', 7.401006458180494)]

In [115]:
tu2.sort(key=lambda t:(-t[1],t[2])) #검정통계량은 크고 pvalue는 작도록 정렬

In [114]:
print(tu2[0:10])

[('U50136_rna1_at', 8.86979372138852, 1.3823856573320467e-10), ('X95735_at', 8.66965836922781, 2.4355284732778464e-10), ('M55150_at', 8.322670912416534, 6.577977412771947e-10), ('M16038_at', 7.401006458180494, 9.846897254435025e-09), ('Y12670_at', 7.3938434923558845, 1.0059685670219272e-08), ('M23197_at', 7.257072533546526, 1.5145322164300762e-08), ('D49950_at', 6.9685428116665085, 3.610124227026674e-08), ('D50063_at', 6.9685428116665085, 0.00608367569067406), ('X17042_at', 6.79232884351761, 6.156940644228055e-08), ('U82759_at', 6.742778448051542, 7.15710601890389e-08)]